package wiki

import scala.util.matching.Regex

sealed class Rule(val pattern: Regex, val page: String, val replacement: Option[String])
sealed class PageRule(pattern: Regex, page: String, replacement: Option[String] = None)
    extends Rule(pattern, page, replacement)
sealed class CategoryRule(
  pattern: Regex,
  page: String,
  val category: Category & Text,
  replacement: Option[String] = None,
) extends Rule(pattern, page, replacement)

object Rules:

  extension (term: String)
    private def insensitive: String = s"(?i)$term"

    private def word: String = s"\\b$term\\b"

    private def notAfterComma: String = s"(?<!\\. ?)$term"

    private def quoted: String = s"${Regex.quote(term)}s?".word.insensitive

    private def notInName: String = s"(?<!\\b(di|i) \\b)$term"

  private def rulesFromPattern(
    f: String => Regex,
  )(entries: (String, String) | (String, String, Category & Text)*): List[Rule] =
    entries.toList.map {
      case (pattern, page)           => PageRule(f(pattern), page)
      case (pattern, page, category) => CategoryRule(f(pattern), page, category)
    }

  private def replacementRulesFromPattern(
    f: String => Regex,
  )(entries: (String, String, String) | (String, String, String, Category & Text)*): List[Rule] =
    entries.toList.map {
      case (pattern, replacement, page)           => PageRule(f(pattern), page, Some(replacement))
      case (pattern, replacement, page, category) => CategoryRule(f(pattern), page, category, Some(replacement))
    }

  private def rulesFromPatternList(
    f: String => Regex,
  )(entries: (List[String], String) | (List[String], String, Category & Text)*): List[Rule] =
    entries.toList.flatMap {
      case (patterns, page)           => patterns.flatMap(pattern => rulesFromPattern(f)((pattern, page)))
      case (patterns, page, category) => patterns.flatMap(pattern => rulesFromPattern(f)((pattern, page, category)))
    }

  private def rulesFromName(entries: String | (String, Category & Text)*): List[Rule] =
    entries.toList.map {
      case name: String     => PageRule(name.quoted.r, name)
      case (name, category) => CategoryRule(name.quoted.r, name, category)
    }

//format: off
  private val eternals = rulesFromPatternList(_.word.r)(
    // Spring
    (List("Arhallogen", "Spider King", "Scorpion Queen", "Centipede General", "Shadow-Hunter", "Sharp Fangs", "Maw-of-Spikes", "Envenomed Blade", "Gasping Breath", "Web of Blades", "Many Move as One", "Skittering Dark", "Wicked Fangs"),
      "Arhallogen", Category.Arhallogen),
    (List("Irra Harah", "Prince with a Thousand Foes", "Papa Otec", "Guard of the Young", "Thorn of the Ancestors", "Shackle Smasher", "The Golden Hare", "il Odioso", "Hateful One"),
      "Irra Harah", Category.IrraHarah),
    (List("Llofir", "[Tt]he Rotlord", "Lady of Spores", "([Tt]he )?Quiet One", "([Tt]he )?Great Fungus", "Wisdom of Dead Wood", "End of Empires", "Inevitable Circle", "[Tt]he Ruin", "Blood Choke"),
      "Llofir", Category.Llofir),
    (List("Ossegrahn", "Lord Rain", "Coomarta of the Rains", "Cupbearer", "Brother Harvest", "Bogfearthan", "Father Tarn", "Llomon", "Elder Fossegrim", "Willowbraid", "Beckburn", "Greenfount"),
      "Ossegrahn", Category.Ossegrahn),
    (List("Siakha", "Maelstrom", "Empress of Sharks", "Schiuma Sanguinosa", "Salt-born Devourer", "Thunder-that-Speaks", "Mother of Wrecks", "Red Squid", "Maw of Stone"),
      "Siakha", Category.Siakha),
    (List("Yaw'nagrah", "Queen of the Forest", "Green Mother", "Rootwinder", "Old Bloodbark", "Verdant Queen", "Lady of the Woods", "Lady of Bark and Bramble", "One who Sways and Stands", "Thorncreeper", "Treecaller", "Woodwyf", "Cornwalker", "Midwife", "Wheatweaver", "Green Hand", "Nest of Thorns", "[Tt]he Plentiful", "Mother of Briars", "Barkspawner"),
      "Yaw'nagrah", Category.`Yaw'nagrah`),
    // Summer
    (List("Adamant", "King Adamant", "King Under the Mountain", "Sharaz", "Throne of Adamant", "Stone Dragon", "Imperishable Potentate", "Master of the Endless Delve", "Throne of Stone", "Deep Dragon", "Wallshaper", "Liege Unbreakable", "Keeper of the Impenetrable Vault"),
      "Adamant", Category.Adamant),
    (List("Barien", "Iron Duke", "Seneschal of the Road", "Lord of the Crossroads", "Knight of the Long Road", "Host of Hosts", "[Tt]he Traveller", "Master of Challenges", "Keeper of the Revels", "Reeve of the Summer Lands", "Barien Dragonforge", "Iron-Staff", "Lord of the Arena"),
      "Barien", Category.Barien),
    (List("Cathan Canae", "Queen of Ice and Darkness", "Lady of the Frost", "Breath of Winter", "Mistress of Blizzards", "Immovable One"),
      "Cathan Canae", Category.CathanCanae),
    (List("Eleonaris", "Queen of the Fields of Glory", "Lady of Pennants", "Commander of the Golden Armies", "Sovereign in Scarlet and Gold", "Lion of Summer", "Sun Drake"),
      "Eleonaris", Category.Eleonaris),
    (List("Hayaak", "Gryphon-King", "Prince-in-Exile", "Brother of Lions", "Hawk Lord", "Blood Eagle"),
      "Hayaak", Category.Hayaak),
    (List("Jaheris", "Unicorn King", "Unicorn Prince", "Lord of the Forest of Arden", "Moonsilver King", "Silverbrow", "Shadowed King", "Lord of Despite", "Regent of the Spiderlands", "Magister of the Argent Tower", "Moonbow", "Cunning Wolf"),
      "Jaheris", Category.Jaheris),
    (List("Meraud", "Summer Enchanter", "Golden Magician", "Lord of Summer Stars", "Fire Mage", "Lord of the Lake"),
      "Meraud", Category.Meraud),
    (List("Rhianos", "King Rhianos", "Queen Rhianos", "Regent of the Eternal Sea", "Foamfollower", "Bottlenose", "Lord Gullscry", "Lady Gullscry", "Hornsounder", "Wind-at-the-Back", "Homebreaker", "Pathtwister", "Deathpiper", "Furole", "Quicksilver", "Glimmerbreeze", "Corposant", "Dancing Merlin", "Azure Songbird", "Bright Zephyr", "Booming Avalanche", "Endless Voyage", "Diving Falcon", "Treasure Giver", "Golden Shatterspray", "Lightning Fish", "Leaping Salmon", "Roaring Wavefather", "Mother of the Wildest", "[Tt]he Waverider", "Tiger's Eye", "Shimmergold", "Stormchaser", "Sail Runner", "Second Strike", "Coruscating Oarfish", "[Tt]he Seadragon", "Windweaver", "Spume Sailor", "Tide Dancer", "Ocean Caller", "Leaf-on-the-Breeze", "Auspicious Mariner", "Laird of the Golden Tides", "Sailor on the Sunlit Sea", "Lord of the Argent Rime", "King of the Nine Tides", "Lady of the Far Horizon", "Master of the Far Shore", "Lord of the Rolling Waves"),
      "Rhianos", Category.Rhianos),
    // Autumn
    (List("Basileia", "Basileia Brazen", "[Tt]he Brazen", "Princess of Weirs", "Carver of Cliques", "Crown of the Archway", "Mistress of Falls", "Patron of Spies and Traitors", "Princess of the Black Vaults"),
      "Basileia", Category.Basileia),
    (List("Callidus", "Prince of the Argent Tontine", "Sovereign-Lord of the City of Chains", "Golden Bargainer", "Keeper of the Gilded Chains", "Satrapy of Hunger", "Drooling Maw"),
      "Callidus", Category.Callidus),
    (List("Ephisis", "Hidden Prince", "[Tt]he Accounter", "High Merchant", "Lady of the Counting House", "Sovereign Lady of the City of Gold and Lead", "Prince of Scales", "Invisible Hand", "Merchant Queen", "Grand Plutocrat"),
      "Ephisis", Category.Ephisis),
    (List("Estavus", "[Tt]he Forgemistress", "Sovereign Lord of the City of Fire and Stone", "Prince of Shikal", "Bronze Artisan", "Towers of Calx and Coom", "Hammer of Fire and Stone"),
      "Estavus", Category.Estavus),
    (List("Mazen", "Mazen of the Many Faces", "Lord of the Masks", "Price of Folly", "Unseen Hand", "Gull-Catcher"),
      "Mazen", Category.Mazen),
    (List("Prospero", "Golden Prince", "Weaver", "Lord of the Loom", "Sovereign Lord of the City of Bridges", "Prince of Ties", "Reckoner of Ebony and Bone", "Golden Spider", "Threadweaver", "Cloven-hoofed", "Polymitarius", "el tejedor", "Jemný Pavouk", "Skredderen"),
      "Prospero", Category.Prospero),
    (List("Sinokenon", "Apex Hyperion", "Friend Of All", "Silver Sovereign", "Singular Point", "That Which Lies Above All", "Way of Hierarchy", "Diamondmind", "That Which Lives In Its Name", "Argent Mantra", "Turning Mirror", "Tomorrow And Tomorrow", "Wheel Of Light"),
      "Sinokenon", Category.Sinokenon),
    (List("Lictors", "[Tt]he Punishers", "[Tt]he Hunters", "Sovereign Lords of the City of Bar and Bond", "Chainbound", "[Tt]he Binders", "Brass Magistrates", "([Tt]he )?Furious Ones", "Reckoners"),
      "Lictors", Category.Lictors),
    // Winter
    (List("Agramant", "[Tt]he Howler", "[Tt]he Hunter", "Wendigo", "Devourer of the Fallen", "Voice (of|in) the Pines", "Blood-on-the-Snow", "Dream of Famine", "[Tt]he Whisperer", "[Tt]he Wastewalker", "([Tt]he )?Abominable One", "Horned Manticore", "Harvester of Graves", "Old Bloody Teeth", "Scrandaddy", "Twigsnap", "Giver of Gifts", "Wicked Liar", "Good Night", "Five True Words", "Friend of the Fearful", "Crying Child", "King of the Feast", "Faithful Friend"),
      "Agramant", Category.Agramant),
    (List("Kaela", "Lady of the Grim Host", "Sorrowful One", "End-of-Strength", "Lady of Oblivion", "Cold-Hearted", "Dark-Between-The-Stars", "Queen of Silence", "([Tt]he )?Black Dog", "Queen Esk", "la Reine qui siège sur le Trône Noir"),
      "Kaela", Category.Kaela),
    (List("Sorin", "Hungry Wolf", "Tomb King", "Empty One", "Devourer-of-Hope", "Hunger-Crow", "Father of Draughir", "Master of Whelps"),
      "Sorin", Category.Sorin),
    (List("Thrice-cursed Court", "[Tt]he Bound(?! King)", "[Tt]he Three"),
      "The Thrice-cursed Court", Category.ThriceCursedCourt),
    (List("Tharim", "([Tt]he )?Bound King", "Stoneheart"),
      "Tharim", Category.Tharim),
    (List("Skathe", "Hag Queen"),
      "Skathe", Category.Skathe),
    (List("Surut", "Charred Prince", "Ashen Knight", "Burnt Steward"),
      "Surut", Category.Surut),
    (List("Wise Rangara", "[Tt]he Wise", "([Tt]he )?Ancient One", "[Tt]he Eldest", "Grandmother Winter", "Kind Rangara", "Pale Raven", "Clever Spider", "White Eye Serpent", "([Tt]he )?Cruel Lady", "[Tt]he Crone"),
      "Wise Rangara", Category.WiseRangara),
    (List("Zakalwe", "Master Strategist", "General of Day", "Weapon-wise", "Hunter of Tides", "Zakalwe Dieu de la Guerre", "Strategos", "Manush", "Brilliant Javelin"),
      "Zakalwe", Category.Zakalwe),
    // Day
    (List("Cold Sun"),
      "Cold Sun", Category.ColdSun),
    (List("Kimus", "Unblinking Eye", "Celestial Eye", "She Who Watches", "Thousand Eyes of the Sun and Moon", "Glass of the Heavens", "Seer Clad in Veils of Light", "del sátrapa de la aurora", "High Mandarin", "First Minister", "Grand Vizier"),
      "Kimus", Category.Kimus),
    (List("Leviathan", "([Tt]he )?Deepest One", "[Tt]he Foundation", "Dweller in the Depths", "Abyssal Lord", "Fish of Why?", "Watcher Beneath the Waters", "She-Who-Counts-The-Ripples", "Unspeakable One Who Lies Beneath ([Tt]he )?Eternal Ocean"),
      "Leviathan", Category.Leviathan),
    (List("Phaleron", "([Tt]he )?Great Library", "Vault of Phaleron", "Archives of Silence", "Coral Library", "Celestial Library"),
      "Phaleron", Category.Phaleron),
    (List("Roshanwe", "[Tt]he Navigator", "Walker on the Littoral", "[Tt]he Mariner", "Elder Pharos", "[Tt]he Fisherman", "Weaver of Nets", "[Tt]he Beachcomber"),
      "Roshanwe", Category.Roshanwe),
    (List("Sung", "Rainbow Serpent", "Whispering Wind", "Night Singer", "Feather on the Breeze", "Lady of Mysteries", "Lord of Illusions", "Spiral Dancer", "Everflowing River", "Neznámy Otázka", "one who hides the truth under its wings", "Moon Moth"),
      "Sung", Category.Sung),
    (List("Ylenwe", "Dove", "Dove of the Perfect Morning", "[Tt]he Morningstar", "Pathway to Serenity", "Nested Interval", "Morning Glory", "Epsilon Close", "Childe of Gentleness", "Cradlesong", "Silk Mask"),
      "Ylenwe", Category.Ylenwe),
    // Night
    (List("Azoth", "[Tt]he Crucible", "[Tt]he Rebis", "([Tt]he )?Great Work"),
      "Azoth", Category.Azoth),
    (List("Janon", "Shadowed Fire", "Muse of Fire", "Firebrand", "Torchbearer", "Night Sword"),
      "Janon", Category.Janon),
    (List("Lashonar", "Gibbering Lashonar", "Lashonar the Loquacious", "Guardian of the Southern Skies", "Keeper of the Gates of Wisdom", "Eater-of-Silence", "Speaker in Dreams", "Conscience-of-Kings"),
      "Lashonar", Category.Lashonar),
    (List("Sadogua", "Brother of Wizards", "Toad King", "Wyrm-King", "Father of Bats", "[Tt]he Glutton", "[Tt]he Lazy", "Black Sloth", "Shuttered Lantern", "Eater of Secrets", "Globberslotch", "Oracle Pig", "Forfører", "o Patrício astuto", "Wujek Sadogua", "Spell Glutton"),
      "Sadogua", Category.Sadogua),
  )

  private val varushkanSovereigns = rulesFromPatternList(_.quoted.word.insensitive.r)(
    (List("Charnel Lord", "Lord of the Crows", "Battlefed", "Moundshroud", "King Beneath the Hill", "Branocbound", "Irontooth", "Boyar of the Broken Barrow"),
      "Charnel Lord", Category.CharnelLord),
    (List("Night Below", "Blackdamp", "Waiting Dark", "Grasping Dark", "Thieving Dark", "Fly-the-light", "Shadow-in-shadows", "Eyes in the Night", "Dark-Below-The-Mountain", "Extinguished Sun", "Shadowcreeper", "Watcher-in-the-Corner", "Nights-haven", "Black-heart", "Abyssal Lady"),
      "Night Below", Category.NightBelow),
    (List("Dho'uala", "Spirit of Dark Water", "Light-in-the-Depths", "Netripper", "Undertow", "Queen of the Drowned", "She-Who-Keeps-What-She-Catches", "Lady of the Semmerlak"),
      "Dho'uala", Category.`Dho'uala`),
  )
//format: on
  private val nations             = rulesFromPatternList(_.quoted.word.insensitive.r)(
    (List("Imperial Orcs"), "Imperial Orcs", Category.ImperialOrcs),
    (List("Navarr", "Navarri"), "Navarr", Category.Navarr),
    (List("Urizen", "Urizeni"), "Urizen", Category.Urizen),
    (List("Varushka", "Varushkan"), "Varushka", Category.Varushka),
    (List("Brass Coast", "Freeborn"), "The Brass Coast", Category.BrassCoast),
    (List("Highguard", "Highborn"), "Highguard", Category.Highguard),
    (List("Wintermark", "Winterfolk"), "Wintermark", Category.Wintermark),
  ) ++ rulesFromPatternList(_.word.notAfterComma.r)(
    (List("Dawn", "[Dd]awnish"), "Dawn", Category.Dawn),
    (List("([Tt]he )?League", "[Ll]eaguer", "city-folk"), "The League", Category.League),
    (List("([Tt]he )?Marches", "Marcher"), "The Marches", Category.Marches),
  )

  private val foreignNations = rulesFromName(
    "Axos"             -> Category.Axos,
    "Asavea"           -> Category.Asavea,
    "Commonwealth"     -> Category.Commonwealth,
    "Faraden"          -> Category.Faraden,
    "Iron Confederacy" -> Category.IronConfederacy,
    "Skoura"           -> Category.Skoura,
    "Otkodov"          -> Category.Otkodov,
    "Tsark"            -> Category.Tsark,
  ) ++ rulesFromPattern(_.word.insensitive.r)(
    ("(Principalities of )?Jarm", "Principalities of Jarm", Category.Jarm),
    ("Sarcophan( Delves)?", "Sarcophan Delves", Category.Sarcophan),
    ("Sumaah( Republic)?", "Sumaah Republic", Category.Sumaah),
  )

  private val barbarianNations = rulesFromName(
    "Druj"    -> Category.Druj,
    "Grendel" -> Category.Grendel,
    "Jotun"   -> Category.Jotun,
    "Thule"   -> Category.Thule,
  )

  private val regions = replacementRulesFromPattern(_.notInName.word.r)(
    List(
      // Brass Coast
      ("Kahraman", "Brass Coast"),
      ("Madruga", "Brass Coast"),
      ("Segura", "Brass Coast"),
      ("Feroz", "Brass Coast"),
      // Dawn
      ("Astolat", "Dawn"),
      ("Semmerholm", "Dawn"),
      ("Weirwater", "Dawn"),
      ("The Barrens", "Dawn"),
      // Highguard
      ("Bastion", "Highguard"),
      ("Casinea", "Highguard"),
      ("Necropolis", "Highguard"),
      ("Reikos", "Highguard"),
      // Imperial Orcs
      ("Skarsind", "Imperial Orcs"),
      ("Mareave", "Imperial Orcs"),
      // The League
      ("Holberg", "The League"),
      ("Sarvos", "The League"),
      ("Tassato", "The League"),
      ("Temeschwar", "The League"),
      // The Marches
      ("Mitwold", "The Marches"),
      ("Mournwold", "The Marches"),
      ("Bregasland", "The Marches"),
      ("Upwold", "The Marches"),
      // Navarr
      ("Hercynia", "Navarr"),
      ("Miaren", "Navarr"),
      ("Therunin", "Navarr"),
      ("Liathaven", "Navarr"),
      // Urizen
      ("Morrow", "Urizen"),
      ("Redoubt", "Urizen"),
      ("Zenith", "Urizen"),
      ("Spiral", "Urizen"),
      ("Sarangrave", "Urizen"),
      // Varushka
      ("Karov", "Varushka"),
      ("Karsk", "Varushka"),
      ("Miekarova", "Varushka"),
      ("Volodmartz", "Varushka"),
      ("Ossium", "Varushka"),
      // Wintermark
      ("Hahnmark", "Wintermark"),
      ("Sermersuaq", "Wintermark"),
      ("Kallavesa", "Wintermark"),
      ("Skallahn", "Wintermark"),
    ).map((territory, nation) => (s"$territory(,? $nation)?", s"$territory, $nation", territory))*,
  ) ++ rulesFromPattern(_.word.insensitive.r)(
    ("Broc[eé]liande", "Brocéliande"),
  )

  private val sovereignty = rulesFromName(
    "Imperial Senate",
    "Imperial Synod",
    "Imperial Conclave",
    "Imperial Bourse",
    "Imperial Military Council",
    "The Throne",
    // Conclave Orders
    "The Celestial Arch",
    "The Sevenfold Path",
    "The Rod and Shield",
    "The Golden Pyramid",
    "The Shuttered Lantern",
    "The Unfettered Mind",
    "The Silver Chalice",
    // Archmage titles
    "Archmage of Spring",
    "Archmage of Summer",
    "Archmage of Autumn",
    "Archmage of Winter",
    "Archmage of Day",
    "Archmage of Night",
  )

  private val springRituals = rulesFromName(
    "Blood of the Hydra",
    "The Hands of Sacred Life",
    "Hearthfire Circle",
    "Chirurgeon's Healing Touch",
    "Fountain of Life",
    "Vitality of Rushing Water",
    "Irrepressible Monkey Spirit",
    "Skin of Bark, Blood of Amber",
    "Rivers of Life",
    "Blessing of New Spring",
    "Fan the Flame of New Life",
    "Churning Cauldron of Bravash",
    "Rampant Growth",
    "Hallow of the Green World",
    "Fire in the Blood",
    "Touch of Vile Humours",
    "Unending Cascade of Blood's Fire",
    "Curse of Gangrenous Flesh",
    "Fetid Breath of Teeming Plague",
    "Rivers Run Red",
    "Call Down Lightning's Wrath",
    "Blood and Salt",
    "Merciless Wrath of the Reaver",
    "Foam and Spittle of the Furious Sea",
    "Thunderous Deluge",
    "Turns the Circle",
    "The Forest Remains",
    "Rising Roots that Rend Stone",
    "Thunderous Tread of the Trees",
  )

  private val summerRituals = rulesFromName(
    "Renewed Strength of the New Day",
    "Tenacity of Jotra",
    "Swan's Cruel Wing",
    "Swift Leaping Hare",
    "Hammer of Thunder",
    "Strength of the Bull",
    "Crimson Ward of Summer Stars",
    "Devastating Maul of Inga Tarn",
    "Talon of the Gryphon",
    "Might of the Myrmidon",
    "Unbreakable Behemoth's Strength",
    "Chasuble of Majesty",
    "Swords in the Noonday Sun",
    "Empower",
    "Glorious Crown of Enchantment",
    "Sutannir's Promise",
    "Prowess of the Golden Magician",
    "Mantle of Lordly Might",
    "Champions Shining Resolve",
    "Raise the Standard of War",
    "Challenge the Iron Duke",
    "Glory to the Sovereign",
    "Delve Deep, Beneath the Mountain",
    "Strong Ox, Golden Sun",
    "Thundering Roar of the Lion-bound Horn",
    "Stout Resolve of the Unyielding",
    "Vigour of Youth",
    "The Sound of Drums",
    "Unbreakable Spirit, Unbreakable Blades",
    "Stalwart Stand on Solid Ground",
    "Frozen Citadel of Cathan Canae",
  )

  private val autumnRituals = rulesFromName(
    "Streams of Silver",
    "Rivers of Gold",
    "Chamber of Pallas",
    "Winds of Fortune",
    "The Lure of Distant Shores",
    "Gathering the Harvest",
    "Gift of the Wily Broker",
    "Ephisis' Scale",
    "Before the Throne of Estavus",
    "Twist of Moebius",
    "Like Water Through Your Fingers",
    "Balanced Scales of Lann",
    "The Conspirator's Cloak",
    "Mantle of the Golden Orator",
    "Create Bond",
    "Arcane Mark",
    "Mark of Fellowship",
    "Mark of Ownership",
    "Ties that Bind",
    "Scrivener's Bloodmark",
    "Shared Mastery of the Magician's Guild",
    "Barked Command of the Iron Serjant",
    "Circle of Gold",
    "Sum of the Parts",
    "Bound by Common Cause",
    "Stance of the Constricting Scourge",
    "Brazen Claws of the Lictor",
    "Inescapable Chains of Bitter Glass",
    "Entangle",
    "Hand of the Maker",
    "The Anvil of Estavus",
    "The Blade Bites Back",
    "Smooth Hands Shape the World",
    "Timeless Hammer Rhythm",
    "Shadow of the Bronze Colossus",
    "Call Winged Messenger",
    "Find the Best Path",
    "The Ambassadorial Gatekeeper",
  )

  private val winterRituals = rulesFromName(
    "Withering Touch of Frost",
    "Crumbling Flesh and Withering Limbs",
    "Hungry Grasp of Despair",
    "Naeve's Twisting Blight",
    "Inevitable Collapse into Ruin",
    "Howling Despite of the Yawning Maw",
    "The Grave's Treacherous Edge",
    "Black Iron Blade",
    "Words of Ending",
    "Ravenous Tongue of Entropy",
    "Devastating Scythe of Anguish and Loss",
    "Wind of Mundane Silence",
    "Wither the Seed",
    "Coil of the Black Leech",
    "Icy Maw Devours the Spark of Essence",
    "Gnawing, Endless Hunger",
    "Dreamscape of the Endless Hunt",
    "An Echo of Life Remains",
    "Wisdom of the Balanced Blade",
    "Ruthless Vigilance, Healthy Crop",
    "Whispers through the Black Gate",
    "Tribute to the Thrice-Cursed Court",
    "Pakaanan's Iron Shutters",
    "Hold Back Frozen Hunger",
    "There Is No Welcome Here",
    "Retreat to the White Caves",
    "Ward of the Black Waste",
    "Clarion Call of Ivory and Dust",
    "Pallid Flesh of the Dead King",
    "Sorin's Rite of Agony",
    "Traitor's Fate",
    "Freezing Brand of Irremais",
    "Winter's Ghosts",
    "Hunger of the Draughir",
    "Unyielding Constitution",
    "Fight Tooth and Nail",
    "Unending Onslaught",
    "Wolves of the Hungry Sea",
    "Last Breath Echoes",
    "Fallow Fields and Dried Meat",
    "Mark the Flesh Incorruptible",
    "Quickening Cold Meat",
  )

  private val dayRituals = rulesFromName(
    "Bright Lantern of Ophis",
    "Revelation of the Jewel's Sparkling Heart",
    "Skein of Years",
    "Clear Lens of the Eternal River",
    "Sular's Promise",
    "Eyes of the Sun and Moon",
    "The Eye of the High Places",
    "Gralka's Gift to the Lost Seeker",
    "Bright Eyes Gleam in the Depths",
    "Detect Magic",
    "Piercing Light of Revelation",
    "Swim Leviathan's Depth",
    "All the World in a Grain of Sand",
    "Revelatory Light of the Empyrean Spheres",
    "Solace of Chimes",
    "Crystal Clarity of the Rational Soul",
    "Illuminate the Higher Mind",
    "Ascendance of the Highest Mind",
    "Transcendent Mastery",
    "Peregrine and Ichimos",
    "Clarity of the Master Strategist",
    "Ascetic Star of Atun",
    "Distillation of Diverse Parts",
    "Horizon's Razor Edge",
    "Sign of Aesh",
    "Standing at the Threshold",
    "Crystalline Focus of Aesh",
    "Alignment of Mind and Blade",
    "Kimus' Glaring Eye",
    "Repel",
  )

  private val nightRituals = rulesFromName(
    "Cast Off The Chain of Memory",
    "Infant Starts with a Blank Slate",
    "Incantation's Mystic Mask",
    "Masque of the Blinded Weaver",
    "Secrets for the Shadow Courier",
    "Secrets of the Empty Heart",
    "Riddle Hides the Reward",
    "The Cuckoo's Egg",
    "Drawing the Penumbral Veil",
    "Shroud of Mist and Shadow",
    "Vale of Shadows",
    "Thief's Arcane Gambit",
    "The Eight-spoked Wheel",
    "The Retrograde Wheel",
    "The Twilight Masquerade",
    "Conclave of Trees and Shadow",
    "Align the Celestial Net",
    "Transmogrification of the Soul's Echo",
    "Dripping Echoes of the Fen",
    "Distil the Serpent's Stone",
    "Amalgamation of Silver and Gold",
    "Emulsion of Lye and Lightning",
    "Signs and Portents",
    "Verdant Bounty of the Twilight Bayou",
    "Whispering Shadow Courtiers",
    "Shadowed Glass of Sung",
    "Wondrous Forests of the Night",
    "Secrets of Skilful Artifice",
    "Silver Tongue of Virtue",
    "Rule of Risk and Reward",
    "Sift the Dreamscape's Sands",
    "Freedom of the Soul",
    "The Chamber of Delights",
    "Embrace the Living Flame",
    "Unfettered Anarchy",
    "Still Waters, Running Deep",
  )

  private val religion = rulesFromPattern(_.word.notAfterComma.r)(
    ("([Tt]he )?Way", "The Way", Category.TheWay),
    ("Ambition", "Ambition", Category.Ambition),
    ("Courage", "Courage", Category.Courage),
    ("Loyalty", "Loyalty", Category.Loyalty),
    ("Pride", "Pride", Category.Pride),
    ("Prosperity", "Prosperity", Category.Prosperity),
    ("Vigilance", "Vigilance", Category.Vigilance),
    ("Wisdom", "Wisdom", Category.Wisdom),
  )

  private val bourseResources = rulesFromName("Mithril", "Weirwood", "White Granite", "Ilium")

  private val herbs = rulesFromName(
    "True Vervain",
    "Cerulean Mazzarine",
    "Imperial Roseweald",
    "Marrowort",
    "Bladeroot",
    "Realmsroot",
  )

  private val metals = rulesFromName("Green Iron", "Orichalcum", "Tempest Jade", "Weltsilver")

  private val forestMaterials = rulesFromName("Ambergelt", "Beggar's Lye", "Dragonbone", "Iridescent Gloaming")

  private val materials = rulesFromName("Liao", "True Liao") ++ rulesFromPatternList(_.word.insensitive.r)(
    (List("Crystal Mana", "Mana Crystals?"), "Crystal Mana"),
  )

  private val titles = rulesFromName(
    "Senator",
    "General",
    "Cardinal",
    "Grandmaster",
    "Ambassador",
    "Gatekeeper",
    "Warmage",
  )

  private val locations = rulesFromName("Anvil") ++ rulesFromPattern(_.word.insensitive.r)(
    ("(The )?Sentinel Gate", "Sentinel Gate"),
  )

  private val volodny = rulesFromPatternList(_.word.insensitive.r)(
    (
      List(
        "(The )?Volodny",
        "Bas Celik",
        "Koshiev the White",
        "Górować",
        "(The )?Shadowsmith",
        "Kareina of the Swans",
        "Breknia",
      ),
      "Volodny",
      Category.Volodny,
    ),
  )

  private val heralds = rulesFromName(
    // Heralds of Phaleron (Day)
    "Elioe"     -> Category.Elioe,
    "Lioc"      -> Category.Lioc,
    "Pollaman"  -> Category.Pollaman,
    "Arannia"   -> Category.Arannia,
    "Melchiore" -> Category.Melchiore,
    // Heralds of Prospero (Autumn)
    "Simone"    -> Category.Simone,
    "Dreyfus"   -> Category.Dreyfus,
    // Heralds of Callidus (Autumn)
    "Numis"     -> Category.Numis,
    "Malleas"   -> Category.Malleas,
    "Zand"      -> Category.Zand,
    // Heralds of Jaheris (Summer)
    "Mahine"    -> Category.Mahine,
    "Esmeray"   -> Category.Esmeray,
    // Heralds of Barien (Summer)
    "Revel"     -> Category.Revel,
    "Temper"    -> Category.Temper,
  )

  private val otherSpirits = rulesFromName(
    "Vallorn"  -> Category.Vallorn,
    // Wintermark
    "Sydanjaa" -> Category.Sydanjaa,
  )

  private val magicItems = rulesFromName(
    // Daggers
    "Scorpion's Sting",
    // One-handed Weapons
    "Apprentice's Blade",
    "Biting Blade",
    "Triumphant Blade",
    "Duelist's Scales",
    "Vorpal Sword",
    "Thresher's Cudgel",
    "Thundering Mace",
    "Ironbound Axe",
    "Shieldbreaker",
    "Bravo's Blade",
    "Redwall's Wrath",
    "Stalwart's Sword",
    // Great Weapons
    "Butcher's Cleaver",
    "Reaving Mattock",
    "Dawn's Glory",
    "Giant's Maul",
    "Landsknecht's Zweihänder",
    "Splintering Hammer",
    "Trollslayer's Crescent",
    "Trollhammer",
    "Captain's Command",
    "Woodcutter's Axe",
    // One-handed Spears
    "Razorleaf Hasta",
    "Stumbleroot Spear",
    "Blackwillow Twist",
    "Ironbrand Thorn",
    "Bloodsteel Barb",
    "Oathsworn Spine",
    "Sydanjaa's Call",
    "Winternight Lifestealer",
    "Terunael Warlord",
    "Thorn's Mark",
    // Paired Weapons
    "Rake's Progress",
    "Brother Blades",
    "Earthquake Drummers",
    "Bear Claws",
    // Polearms
    "Farmer's Scythe",
    "Sanguine Spear",
    "Butcher's Bill",
    "Bolstering Bill",
    "Warden's Bardiche",
    "Blacksmith's Wage",
    "Barbed Spear",
    "Magistrate's Grasp",
    "Fell Iron Fury",
    "Bullroarer's Shout",
    "Labyrinth's Gate",
    // Bows
    "Martán's Mark",
    "Vowkeeper",
    "Wayfinder",
    // Arcane Weapons
    "Mountebank's Surprise",
    "Shears of Winter",
    "Warden's Fists",
    "Arms of the Warwitch",
    "Jade Hammers",
    "Binding Threads",
    "Children of Thunder",
    "Trodwalker's Readiness",
    "Thorns of the Rose",
    // Wands
    "Acolyte's Mercy",
    "Mazzarine Spindle",
    "Runesmith's Gavel",
    "Swanfeather Schema",
    "Witchwood Wand",
    "Altruist's Recompense",
    "Redsteel Chisel",
    "Ambergelt Baton",
    "Boneweaver",
    "Bloodwoven Braid",
    "Seer's Probe",
    "Scrivener's Seal",
    "Woundbinder",
    "Grimnir's Hearthfire",
    "Sanguine Thorn",
    // Rods
    "Forlorn Hope",
    "Storm Sceptre",
    "Tactician's Demand",
    "Yeoman's Bounty",
    "Whelpmaster's Fang",
    "Windreaping Sickle",
    "Bloodsilver Spike",
    "Quiet Word",
    "Tumultuous Gyre",
    "Neophyte's Aid",
    "Witches' Hammer",
    "Blood-dimming Tide",
    "Roaring Chimera Rod",
    "Stormweaver",
    "Radiant Torrent",
    "Sceptre of the Necropolis",
    // Staffs
    "Agramant's Bargain",
    "Lamia's Whisper",
    "Landskeeper's Oath",
    "Pugilist's Shillelagh",
    "Unseen Encasement",
    "Shadowbound Donjon",
    "Amberglass Chain",
    "Death's Door",
    "Enfeebling Echo",
    "Furrowed Wake",
    "Staff of Power",
    "Ethereal Manacle",
    "Staff of Command",
    "Staff of Life",
    "Suzerain's Command",
    "Caress of Arhallogen",
    "Staff of Imperial Mastery",
    // Ritual Staves
    "Choleric Staff",
    "Enigmatic Staff",
    "Luminous Staff",
    "Melancholic Staff",
    "Phlegmatic Staff",
    "Sanguine Staff",
    "Staff of the Magi",
    // Icons
    "Icon of the Judge",
    "Icon of the Justicar",
    "Icon of the Pilgrim",
    "Icon of the Seer",
    "Icon of the Smith",
    "Icon of the Steward",
    "Icon of the Witness",
    "Icon of the Devoted",
    "Icon of the Driven",
    "Icon of the Industrious",
    "Icon of the Insightful",
    "Icon of the Proud",
    "Icon of the Righteous",
    "Icon of the Watchful",
    // Musical Instruments
    "Celebrant's Fiddle",
    "Goldwood Pipes",
    "Heroes' Horn",
    "Horn Resounding",
    "Silver Gate",
    "Thundering Drum",
    "Watchers' Flute",
    // Light Armour
    "Stoutheart Gambeson",
    "Soldier's Harness",
    "Jack of Irons",
    "Winter's Breath",
    "Runemark Shirt",
    "Blood-sweat Hauberk",
    "Ivory Aketon",
    "Spiritskin Coat",
    "Mediators Purse",
    // Medium Armour
    "Marauder's Cote",
    "Bloodamber Hauberk",
    "Boarskin Vest",
    "Cerulean Protector",
    "Scrivener's Guard",
    "Runebound Ward",
    "Wardensweave",
    "Tombshroud Guardian",
    "Baersark's Rage",
    // Heavy Armour
    "Warrior's Plate",
    "Enduring Breastplate",
    "Goldentide Mail",
    "Knightly Redoubt",
    "Defiant Steel",
    "Winterborn Warmail",
    "Runeplate",
    "Goldenfire Scale",
    "Gryphonsoul Aegis",
    "Hero's Hauberk",
    // Mage Robes
    "Crystaltender's Vestment",
    "Volhov's Robe",
    "Shimmergold Coat",
    "Opaline Coat",
    "Trollsweave Vest",
    "Robe of Blood and Bone",
    "Glamourweave Robe",
    "Ashen Mantle",
    "Bishop's Ensemble",
    "Captain's Garb",
    "Doctor's Attire",
    "Mountebank's Guise",
    "Prince's Raiment",
    "Semblance of the Witch",
    "Moonsilver Doublet",
    // Mage Armour
    "Hero's Girdle",
    "Splintering Gorget",
    "Wyvernsting Spaulders",
    "Warmage's Belt",
    "Healer's Harness",
    "Sunfire Pectoral",
    "Bloodfeather Harness",
    "Vambraces of Regeneration",
    "Twilight Pauldrons",
    "Gravedigger's Vest",
    "Forge of Isenbrad",
    "Battlesmith's Panoply",
    "Mountainfall Bracers",
    // Vestments
    "Mendicant Cassock",
    "Wayfarer's Robe",
    "Alabaster Cerement",
    "Keeper's Habit",
    "Troubadour's Tunic",
    "Labyrinthine Vestments",
    // Shields
    "Pilgrim's Shield",
    "Oakheart Shield",
    "Stormguard Bulwark",
    "Warcaster's Oath",
    "Burnished Rampart",
    "Champion's Bastion",
    "Runesmith's Glare",
    "Virtuous Ward",
    // Jewellery
    "Circlet of Falling Snow",
    "Dragonbone Symbol",
    "Bondring",
    "Shackle of the Unvirtuous",
    "Alder's Edge",
    "Greensteel Bracelets",
    "Chrysalis Pendant",
    "Troubadour's Ring",
    "Pauper's Key",
    "Bloodfire Periapt",
    "Abraxus Stone",
    "Lowther's Gaze",
    "Circlet of Command",
    // Ritual Masks
    "Straw Mask",
    "Corsair's Bloody Mask",
    "Mask of Gold and Lead",
    "Mercantilist's Mask",
    "Captain's Mask",
    "Mask of the Mountebank",
    "Strigine Mask",
    // Foci
    "Cowl of Ashes",
    "Ring of Adversity",
    "Ring of Triumph",
    "Atun's Ring",
    "Ring of the Rainbow Sage",
    "The Crimson Feast",
    "Four Spirit's Mask",
    "Icewalker's Anvil",
    "Kingfisher's Promise",
    // Tools
    "Escharotic Cauldron",
    "Wyrmstone Mortar",
    "Phial of the Sun",
    "Lodestone Shears",
    "Bloodcloak",
    "Isenbrad's Legacy",
    "Limbsetter's Point",
    // Regalia
    "Guided Path",
    "Beneficent Sigil",
    "Sungold Basin",
    "Blessing Wheel",
    "Brazier of Benediction",
    "Pilgrim's Cup",
    "Fireglass",
    "Cowl of Judgement",
    "Silent Bell",
    "Skein Bowl",
    // Magic Standards
    "Banner of the Bold",
    "Chirurgeon's Ensign",
    "Thaneshall Banner",
    "Sunfire Pennant",
    "Titan's Battlemark",
    "Thorn's Dance",
    "Celestial Sigil",
    "Loyal Stanchion",
    "Warsmith's Shingle",
    "Three Tears",
    // Gonfalon
    "Mercenary Banner",
    // Paraphernalia
    "Amberglass Orb",
    "Burnished Orb",
    "Dragonbone Orb",
    "Greensteel Orb",
    "Radiant Orb",
    "Twilight Orb",
    "Vitriolic Orb",
    "Cartographer's Eye",
    "Orator's Chalice",
    "The Barren Land",
    "The Empty Horizon",
    "The Fields of Glory",
    "The Flickering Flame",
    "The Green World",
    "The Iron Labyrinth",
    "Web of Celestial Attunement",
    "The Eternal Gambit",
    "The Fountain of Thorns",
    "The Key and the Gate",
    "The Mountainous Oak",
    "The Spider's Web",
    "The Drowned Threshold",
    "The Vagabond Wyrm",
    "The Syphon of Stars",
    // Reliquaries
    "Litany of the Labyrinth",
    "Wayfarer's Pyx",
    "Bishop's Chalice",
    "Almery of Silence",
  )

  private val imperialArmies = rulesFromName(
    "Argent Sword"          -> Category.ArgentSword,
    "Autumn Hammers"        -> Category.AutumnHammers,
    "Black Thorns"          -> Category.BlackThorns,
    "Bloodcloaks"           -> Category.Bloodcloaks,
    "Bounders"              -> Category.Bounders,
    "Boyar's Hasta"         -> Category.BoyarsHasta,
    "Burning Falcon"        -> Category.BurningFalcon,
    "Citadel Guard"         -> Category.CitadelGuard,
    "Drakes"                -> Category.Drakes,
    "Eastern Sky"           -> Category.EasternSky,
    "Fire of the South"     -> Category.FireOfTheSouth,
    "Fist of the Mountains" -> Category.FistOfTheMountains,
    "Freeborn Storm"        -> Category.FreebornStorm,
    "Golden Axe"            -> Category.GoldenAxe,
    "Golden Sun"            -> Category.GoldenSun,
    "Granite Pillar"        -> Category.GranitePillar,
    "Green Shield"          -> Category.GreenShield,
    "Gryphon's Pride"       -> Category.GryphonsPride,
    "Hounds of Glory"       -> Category.HoundsOfGlory,
    "Iron Helms"            -> Category.IronHelms,
    "Isaella's Dance"       -> Category.IsaellasDance,
    "Lions of Adelmar"      -> Category.LionsOfAdelmar,
    "Narwhal's Spear"       -> Category.NarwhalsSpear,
    "Northern Eagle"        -> Category.NorthernEagle,
    "Pilgrim's Defiance"    -> Category.PilgrimsDefiance,
    "Quiet Step"            -> Category.QuietStep,
    "Red Wind Corsairs"     -> Category.RedWindCorsairs,
    "Seventh Wave"          -> Category.SeventhWave,
    "Sparrows Reckoning"    -> Category.SparrowsReckoning,
    "Star Forged"           -> Category.StarForged,
    "Strong Reeds"          -> Category.StrongReeds,
    "Summer Storm"          -> Category.SummerStorm,
    "Towerjacks"            -> Category.Towerjacks,
    "Tusks"                 -> Category.Tusks,
    "Valiant Pegasus"       -> Category.ValiantPegasus,
    "Winter Sun"            -> Category.WinterSun,
    "Wolves of War"         -> Category.WolvesOfWar,
  )
  // format: on

  val allRules: List[Rule] = List(
    nations,
    foreignNations,
    barbarianNations,
    regions,
    sovereignty,
    titles,
    locations,
    springRituals,
    summerRituals,
    autumnRituals,
    winterRituals,
    dayRituals,
    nightRituals,
    religion,
    bourseResources,
    metals,
    forestMaterials,
    herbs,
    materials,
    volodny,
    heralds,
    otherSpirits,
    magicItems,
    eternals,
    varushkanSovereigns,
    imperialArmies,
  ).flatten.sortBy(_.page.length)(using Ordering[Int].reverse)
